export enum CompetitionCode {
  // Europa
  'EUROPA_UEFA_CHAMPIONS_LEAGUE' = 'EUROPA_UEFA_CHAMPIONS_LEAGUE',
  'EUROPA_UEFA_EURO_LEAGUE' = 'EUROPA_UEFA_EURO_LEAGUE',
  'EUROPA_UEFA_SUPER_CUP' = 'EUROPA_UEFA_SUPER_CUP',

  // International
  'INTERNATIONAL_EURO_CHAMPIONSHIP' = 'INTERNATIONAL_EURO_CHAMPIONSHIP',
  // 'INTERNATIONAL_CONFEDARATIONS_CUP' = 'INTERNATIONAL_CONFEDARATIONS_CUP',
  'INTERNATIONAL_WORLD_CUP' = 'INTERNATIONAL_WORLD_CUP',
  'INTERNATIONAL_WORLD_CUP_QUALIFICATION_CONCACAF' = 'INTERNATIONAL_WORLD_CUP_QUALIFICATION_CONCACAF',
  'INTERNATIONAL_WORLD_CUP_QUALIFICATION_EUROPE' = 'INTERNATIONAL_WORLD_CUP_QUALIFICATION_EUROPE',
  // 'INTERNATIONAL_FIFA_WORLD_CUP' = 'INTERNATIONAL_FIFA_WORLD_CUP',
  'INTERNATIONAL_UEFA_NATIONS_LEAGUE' = 'INTERNATIONAL_UEFA_NATIONS_LEAGUE',
  'INTERNATIONAL_FRIENDLIES' = 'INTERNATIONAL_FRIENDLIES',

  // Deutschland
  'GERMANY_BUNDESLIGA' = 'GERMANY_BUNDESLIGA',
  'GERMANY_BUNDESLIGA_2' = 'GERMANY_BUNDESLIGA_2',
  'GERMANY_SUPER_CUP' = 'GERMANY_SUPER_CUP',
  'GERMANY_DFB_POKAL' = 'GERMANY_DFB_POKAL',

  // England
  'ENGLAND_PREMIER_LEAGUE' = 'ENGLAND_PREMIER_LEAGUE',
  'ENGLAND_LEAGUE_CUP' = 'ENGLAND_LEAGUE_CUP',
  // 'ENGLAND_EFL_TROPHY' = 'ENGLAND_EFL_TROPHY',
  // 'ENGLAND_FA_TROPHY' = 'ENGLAND_FA_TROPHY',
  'ENGLAND_FA_CUP' = 'ENGLAND_FA_CUP',
  'ENGLAND_COMMUNITY_SHIELD' = 'ENGLAND_COMMUNITY_SHIELD',
  // 'ENGLAND_PREMIER_LEAGUE_CUP' = 'ENGLAND_PREMIER_LEAGUE_CUP',

  // Spanien
  'SPAIN_LA_LIGA' = 'SPAIN_LA_LIGA',
  'SPAIN_SUPER_CUP' = 'SPAIN_SUPER_CUP',
  'SPAIN_COPA_DEL_REY' = 'SPAIN_COPA_DEL_REY',

  // Italien
  'ITALY_SERIE_A' = 'ITALY_SERIE_A',
  // 'ITALY_SUPER_CUP' = 'ITALY_SUPER_CUP',
  'ITALY_COPPA_ITALIA' = 'ITALY_COPPA_ITALIA',

  // Frankreich
  'FRANCE_LIGUE_1' = 'FRANCE_LIGUE_1',
  // 'FRANCE_COUPE_DE_LA_LIGUE' = 'FRANCE_COUPE_DE_LA_LIGUE', -> wurde abgeschafft seit saison 19/20
  'FRANCE_COUPE_DE_FRANCE' = 'FRANCE_COUPE_DE_FRANCE',
  'FRANCE_TROPHEE_DES_CHAMPIONS' = 'FRANCE_TROPHEE_DES_CHAMPIONS',

  // Niederlande
  'EREDIVISIE' = 'EREDIVISIE',

  // USA
  'MAJOR_LEAGUE_SOCCER' = 'MAJOR_LEAGUE_SOCCER',
}
